services:
  workspace:
    build: .
    command: sleep infinity
    volumes:
      - type: bind
        source: ..
        target: /workspaces/aws-localstack-devcontainer
        consistency: cached
    working_dir: /workspace
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
      - '4510-4559:4510-4559'
    environment:
      # - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack:/var/lib/localstack

volumes:
  localstack:
