FROM mcr.microsoft.com/devcontainers/base:ubuntu

# hadolint ignore=DL3008
# RUN export DEBIAN_FRONTEND=noninteractive \
#     && apt-get update \
#     && apt-get -y install --no-install-recommends \
#     ... \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*
